package com.example.iPharmacy.database;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.springframework.data.annotation.Id;

//converted to QuestionSet and Question classes
public class Document {
	
	@Id
	private String id;
	
	private byte[] data;
	
	public Document() {};
	
	public Document(byte[] data) {
		this.data = data.clone();
	}
	
	public Document(String path) throws IOException {
		data = Files.readAllBytes(Path.of(path));
	}

	public String getId() {
		return id;
	}

	//should only be used for testing purposes
	//ID auto-generated by MongoDB
	public void setId(String id) {
		this.id = id;
	}

	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}
	
}
